# Generated by Django 6.0.2 on 2026-02-14 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='reports_cus_email_dc4668_idx'), models.Index(fields=['name'], name='reports_cus_name_30e1d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='reports_pro_name_5e01b1_idx'), models.Index(fields=['price'], name='reports_pro_price_8b8958_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
            ],
            options={
                'indexes': [models.Index(fields=['sale_date'], name='reports_sal_sale_da_9aa81f_idx'), models.Index(fields=['status'], name='reports_sal_status_d33984_idx')],
            },
        ),
    ]
